# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-test-',
                'doc_host': 'https://TowfiqDL.github.io',
                'git_url': 'https://github.com/TowfiqDL/nbdev-test-',
                'lib_path': 'nbdev_test_'},
  'syms': {'nbdev_test_.core': {'nbdev_test_.core.foo': ('core.html#foo', 'nbdev_test_/core.py')}}}
